GET http://localhost:3001/api/info

###
# Get all persons
GET http://localhost:3001/api/persons/ 

###
# Get person by ID
GET http://localhost:3001/api/persons/661d90a0a7696cf8b148623c

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Bryan",
    "number": "123456789"
}

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "number": "123456789"
}

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Bryan"
}

###
// Non-unique name
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "123456789"
}