GET http://localhost:3001/api/info

###
# Get all persons
GET http://localhost:3001/api/persons/ 

###
# Get person by ID
GET http://localhost:3001/api/persons/661d90a0a7696cf8b148623c

###
# Malformed ID to trigger error message
GET http://localhost:3001/api/persons/{}

###
# Delete by ID
DELETE http://localhost:3001/api/persons/661d90a0a7696cf8b148623c

###
# Update by ID
PUT http://localhost:3001/api/persons/661d75e121af59eaea197274
content-type: application/json

{
    "name": "Bryan S",
    "number": "830-8929"
}

###
# Valid POST submission
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Bryan",
    "number": "123-456789"
}

###
# Invalid POST - Phone number is not long enough
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Bryan",
    "number": "123-45"
}

###
# Invalid POST - Malformed phone number
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Bryan",
    "number": "10-22-334455"
}

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "number": "123456789"
}

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Bryan"
}

###
// Non-unique name
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "123456789"
}